#!/usr/bin/env node
/**
 * Regression tests for engine/core/cvss40.mjs.
 *
 * The 15 PINNED_VECTORS below are not hand-typed guesses. They were
 * generated by cross-validating this module against the UNMODIFIED official
 * FIRST reference implementation (cvss_score.js from
 * github.com/FIRSTdotorg/cvss-v4-calculator, loaded raw via Node's vm module
 * as an independent oracle) across 2000 randomly-generated valid CVSS 4.0
 * vectors (1000 base-metric-only, 1000 also varying E/CR/IR/AR) — 0
 * mismatches. These 15 are a deterministic (seeded, not Math.random) sample
 * from that run, so this test file is self-contained and oracle-free for
 * everyday CI, while still tracing back to a real independent verification.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { cvss40Score, cvss40Severity, parseVector } from '../engine/core/cvss40.mjs';

const PINNED_VECTORS = [
  { vector: 'CVSS:4.0/AV:L/AC:H/AT:P/PR:H/UI:A/VC:N/VI:L/VA:H/SC:H/SI:H/SA:H', score: 6 },
  { vector: 'CVSS:4.0/AV:P/AC:H/AT:P/PR:L/UI:N/VC:H/VI:N/VA:N/SC:N/SI:L/SA:H', score: 5.7 },
  { vector: 'CVSS:4.0/AV:P/AC:L/AT:P/PR:H/UI:A/VC:H/VI:L/VA:L/SC:H/SI:H/SA:L', score: 6 },
  { vector: 'CVSS:4.0/AV:P/AC:L/AT:P/PR:N/UI:P/VC:L/VI:L/VA:N/SC:N/SI:N/SA:H', score: 1.8 },
  { vector: 'CVSS:4.0/AV:P/AC:L/AT:P/PR:N/UI:A/VC:H/VI:H/VA:L/SC:H/SI:H/SA:N', score: 7 },
  { vector: 'CVSS:4.0/AV:N/AC:L/AT:P/PR:H/UI:P/VC:N/VI:L/VA:L/SC:H/SI:H/SA:H', score: 5.2 },
  { vector: 'CVSS:4.0/AV:P/AC:H/AT:N/PR:H/UI:N/VC:L/VI:H/VA:H/SC:H/SI:L/SA:L', score: 5.9 },
  { vector: 'CVSS:4.0/AV:P/AC:L/AT:N/PR:L/UI:P/VC:L/VI:H/VA:N/SC:L/SI:N/SA:H', score: 6.8 },
  { vector: 'CVSS:4.0/AV:L/AC:H/AT:P/PR:L/UI:P/VC:L/VI:H/VA:H/SC:H/SI:L/SA:H', score: 6 },
  { vector: 'CVSS:4.0/AV:P/AC:H/AT:P/PR:N/UI:A/VC:L/VI:L/VA:H/SC:H/SI:N/SA:N', score: 5.7 },
  { vector: 'CVSS:4.0/AV:A/AC:H/AT:P/PR:H/UI:P/VC:H/VI:L/VA:H/SC:N/SI:L/SA:N', score: 4.6 },
  { vector: 'CVSS:4.0/AV:L/AC:L/AT:N/PR:L/UI:P/VC:N/VI:H/VA:N/SC:N/SI:L/SA:L', score: 5.1 },
  { vector: 'CVSS:4.0/AV:L/AC:L/AT:P/PR:N/UI:N/VC:H/VI:H/VA:N/SC:L/SI:H/SA:N', score: 8.6 },
  { vector: 'CVSS:4.0/AV:A/AC:H/AT:P/PR:N/UI:N/VC:L/VI:N/VA:L/SC:H/SI:N/SA:N', score: 4.9 },
  { vector: 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:P/VC:H/VI:N/VA:H/SC:H/SI:H/SA:L', score: 8.5 },
];

test('all 15 oracle-cross-validated pinned vectors score correctly', () => {
  for (const { vector, score } of PINNED_VECTORS) {
    const got = cvss40Score(vector);
    assert.equal(got, score, `${vector} expected ${score}, got ${got}`);
  }
});

test('zero-impact vector scores exactly 0.0', () => {
  assert.equal(cvss40Score('CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:N/SC:N/SI:N/SA:N'), 0.0);
});

test('maximum-severity vector scores in the Critical band', () => {
  const s = cvss40Score('CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:H/SI:H/SA:H');
  assert.ok(s >= 9.0, `expected Critical (>=9.0), got ${s}`);
  assert.equal(cvss40Severity(s), 'Critical');
});

test('severity bands match FIRST qualitative ranges', () => {
  assert.equal(cvss40Severity(0), 'None');
  assert.equal(cvss40Severity(3.9), 'Low');
  assert.equal(cvss40Severity(4.0), 'Medium');
  assert.equal(cvss40Severity(6.9), 'Medium');
  assert.equal(cvss40Severity(7.0), 'High');
  assert.equal(cvss40Severity(8.9), 'High');
  assert.equal(cvss40Severity(9.0), 'Critical');
  assert.equal(cvss40Severity(10), 'Critical');
});

test('rejects a CVSS 3.1 vector', () => {
  assert.throws(() => cvss40Score('CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N'));
});

test('rejects a vector missing a mandatory base metric', () => {
  assert.throws(() => parseVector('CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N'));
});

test('rejects an invalid metric value', () => {
  assert.throws(() => parseVector('CVSS:4.0/AV:Z/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N'));
});

test('optional metrics default to X and do not require specification', () => {
  const withoutOptional = cvss40Score('CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N');
  const withExplicitX = cvss40Score('CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X');
  assert.equal(withoutOptional, withExplicitX);
});
